name = "LRATCatcher"
defaultTargets = ["LRATCatcher"]

[[lean_lib]]
name = "LRATCatcher"

[[lean_exe]]
name = "lratcatch-export"
root = "Export"

[[lean_exe]]
name = "lratcatch-gen"
root = "Gen"

[[lean_exe]]
name = "lratcatch-cover-parallel"
root = "CoverParallel"

[[lean_exe]]
name = "lratcatch-cover-stream"
root = "CoverStream"

[[lean_exe]]
name = "lratcatch-stream-gen"
root = "StreamGen"

[[lean_exe]]
name = "lratcatch-normalize"
root = "Normalize"

[[lean_exe]]
name = "lratcatch-compact-renumber"
root = "CompactRenumber"
