import LRATCatcher.Cover

/-!
  End-to-end cube-and-conquer test: PHP(4,3) split on variable 1 into two cubes.
  Leaf and cover certificates produced by CaDiCaL (`--lrat --no-binary`);
  leaf CNFs and the negated-cubes CNF generated by `lratcatch-export`.
-/

namespace LRATCatcher.Tests

lrat_cover_reflect php43_unsat
  "examples/php43/base.cnf" "examples/php43/cubes.icnf"
  "examples/php43/leaf" "examples/php43/cover.lrat"

#print axioms php43_unsat

end LRATCatcher.Tests
